// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvmz9JnxpcEjSlzkJ4QtPP4i00iVMj8W0',
    appId: '1:968459575564:web:a6ed11ff9d7145075c6929',
    messagingSenderId: '968459575564',
    projectId: 'hotel-booking-fc756',
    authDomain: 'hotel-booking-fc756.firebaseapp.com',
    storageBucket: 'hotel-booking-fc756.firebasestorage.app',
    measurementId: 'G-SCW2DY3R4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZWoBs4KXO5Ydzv4VAU87fbvJugEBULt4',
    appId: '1:968459575564:android:ff557e335d73ea1e5c6929',
    messagingSenderId: '968459575564',
    projectId: 'hotel-booking-fc756',
    storageBucket: 'hotel-booking-fc756.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzw6NjK8KpAT8dDHUZKJEQsn4ShNuO4m4',
    appId: '1:968459575564:ios:a9faebe8139c84375c6929',
    messagingSenderId: '968459575564',
    projectId: 'hotel-booking-fc756',
    storageBucket: 'hotel-booking-fc756.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzw6NjK8KpAT8dDHUZKJEQsn4ShNuO4m4',
    appId: '1:968459575564:ios:a9faebe8139c84375c6929',
    messagingSenderId: '968459575564',
    projectId: 'hotel-booking-fc756',
    storageBucket: 'hotel-booking-fc756.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvmz9JnxpcEjSlzkJ4QtPP4i00iVMj8W0',
    appId: '1:968459575564:web:a6141feb9004e5b25c6929',
    messagingSenderId: '968459575564',
    projectId: 'hotel-booking-fc756',
    authDomain: 'hotel-booking-fc756.firebaseapp.com',
    storageBucket: 'hotel-booking-fc756.firebasestorage.app',
    measurementId: 'G-C9PD8DEK9T',
  );
}
